#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Mon Nov 21 17:12:03 2022
#

import wx
from windows_systems_utils import *
from web_browser_utils import *
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainPanel(wx.Frame):
    temp_files: bool = False
    sys_temp_files: bool = False
    web_cache: bool = False
    web_cookies: bool = False
    recycle_bin: bool = False
    old_windows_installs: bool = False
    downloads_folder: bool = False

    files_deleted = 0.0

    def __init__(self, *args, **kwds):
        # begin wxGlade: MainPanel.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((750, 464))
        self.SetTitle("DocPy")
        self.SetIcon(wx.Icon("./DocPyIcoLarge.ico", wx.BITMAP_TYPE_ICO))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.V_Split = wx.SplitterWindow(self.panel_1, wx.ID_ANY)
        self.V_Split.SetMinimumPaneSize(20)
        sizer_1.Add(self.V_Split, 1, wx.EXPAND, 0)

        self.Options_Menu = wx.Panel(self.V_Split, wx.ID_ANY)

        Options_List = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_2, 1, wx.EXPAND, 0)

        self.temp_file_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_2.Add(self.temp_file_checkbox, 0, wx.ALL, 15)

        temp_file_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "User Temporary Files")
        sizer_2.Add(temp_file_label, 0, wx.ALL, 15)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_3, 1, wx.EXPAND, 0)

        self.sys_temp_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_3.Add(self.sys_temp_files_checkbox, 0, wx.ALL, 15)

        sys_temp_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "System Temporary Files")
        sizer_3.Add(sys_temp_files_label, 0, wx.ALL, 15)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_4, 1, wx.EXPAND, 0)

        self.web_cache_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_4.Add(self.web_cache_files_checkbox, 0, wx.ALL, 15)

        web_cache_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Web Cache")
        sizer_4.Add(web_cache_files_label, 0, wx.ALL, 15)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_5, 1, wx.EXPAND, 0)

        self.web_cookies_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_5.Add(self.web_cookies_files_checkbox, 0, wx.ALL, 15)

        web_cookies_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Web Cookies")
        sizer_5.Add(web_cookies_files_label, 0, wx.ALL, 15)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_6, 1, wx.EXPAND, 0)

        self.windows_installs_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_6.Add(self.windows_installs_files_checkbox, 0, wx.ALL, 15)

        windows_install_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Old Windows Install Files")
        sizer_6.Add(windows_install_files_label, 0, wx.ALL, 15)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_7, 1, wx.EXPAND, 0)

        self.recycle_bin_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_7.Add(self.recycle_bin_files_checkbox, 0, wx.ALL, 15)

        recycle_bin_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Recycle Bin")
        sizer_7.Add(recycle_bin_files_label, 0, wx.ALL, 15)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_8, 1, wx.EXPAND, 0)

        self.user_downloads_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_8.Add(self.user_downloads_files_checkbox, 0, wx.ALL, 15)

        user_downloads_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Downloads Folder")
        sizer_8.Add(user_downloads_files_label, 0, wx.ALL, 15)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_12, 1, wx.EXPAND, 0)

        self.analyze_button = wx.Button(self.Options_Menu, wx.ID_ANY, "Analyze")
        sizer_12.Add(self.analyze_button, 0, wx.ALL, 15)

        self.clean_button = wx.Button(self.Options_Menu, wx.ID_ANY, "Clean")
        sizer_12.Add(self.clean_button, 0, wx.ALL, 15)

        self.Status_Pane = wx.Panel(self.V_Split, wx.ID_ANY)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)

        static_line_1 = wx.StaticLine(self.Status_Pane, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_11.Add(static_line_1, 0, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.Status_Pane, wx.ID_ANY)
        sizer_11.Add(self.panel_2, 1, wx.EXPAND, 0)

        sizer_9 = wx.BoxSizer(wx.VERTICAL)

        self.size_of_files_deleted_label = wx.StaticText(self.panel_2, wx.ID_ANY, "Files Deleted")
        self.size_of_files_deleted_label.SetMinSize((66, 250))
        sizer_9.Add(self.size_of_files_deleted_label, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 15)

        doc_py_credits = wx.StaticText(self.panel_2, wx.ID_ANY, "DocPy :: Kyle Stevens 2022 - It's all gone to shit...")
        sizer_9.Add(doc_py_credits, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 15)

        self.panel_2.SetSizer(sizer_9)

        self.Status_Pane.SetSizer(sizer_11)

        self.Options_Menu.SetSizer(Options_List)

        self.V_Split.SplitVertically(self.Options_Menu, self.Status_Pane, 215)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.temp_file_checkbox.Bind(wx.EVT_CHECKBOX, self.temp_file_checkbox_handler)
        self.sys_temp_files_checkbox.Bind(wx.EVT_CHECKBOX, self.sys_temp_file_checkbox_handler)
        self.web_cache_files_checkbox.Bind(wx.EVT_CHECKBOX, self.web_cache_checkbox_handler)
        self.web_cookies_files_checkbox.Bind(wx.EVT_CHECKBOX, self.web_cookies_checkbox_handler)
        self.windows_installs_files_checkbox.Bind(wx.EVT_CHECKBOX, self.windows_install_checkbox_handler)
        self.recycle_bin_files_checkbox.Bind(wx.EVT_CHECKBOX, self.recycle_bin_checkbox_handler)
        self.user_downloads_files_checkbox.Bind(wx.EVT_CHECKBOX, self.downloads_folder_checkbox_handler)
        self.analyze_button.Bind(wx.EVT_BUTTON, self.analyze_button_handler)
        self.clean_button.Bind(wx.EVT_BUTTON, self.clean_button_handler)
        # end wxGlade

    def temp_file_checkbox_handler(self, event):  # wxGlade: MainPanel.<event_handler>
        self.temp_files = not self.temp_files
        event.Skip()

    def sys_temp_file_checkbox_handler(self, event):  # wxGlade: MainPanel.<event_handler>
        self.sys_temp_files = not self.sys_temp_files
        event.Skip()

    def web_cache_checkbox_handler(self, event):  # wxGlade: MainPanel.<event_handler>
        self.web_cache = not self.web_cache
        event.Skip()

    def web_cookies_checkbox_handler(self, event):  # wxGlade: MainPanel.<event_handler>
        self.web_cookies = not self.web_cookies
        event.Skip()

    def windows_install_checkbox_handler(self, event):  # wxGlade: MainPanel.<event_handler>
        self.old_windows_installs = not self.old_windows_installs
        event.Skip()

    def recycle_bin_checkbox_handler(self, event):  # wxGlade: MainPanel.<event_handler>
        self.recycle_bin = not self.recycle_bin
        event.Skip()

    def downloads_folder_checkbox_handler(self, event):  # wxGlade: MainPanel.<event_handler>
        self.downloads_folder = not self.downloads_folder
        event.Skip()

    def analyze_button_handler(self, event):  # wxGlade: MainPanel.<event_handler>
        print(self.temp_files,self.sys_temp_files,self.web_cache,self.web_cookies,self.recycle_bin,self.old_windows_installs,self.downloads_folder)
        files_deleted_size = 0
        if self.temp_files:
            files_deleted_size += (analyze_user_temp_files())
        if self.sys_temp_files:
            files_deleted_size += (analyze_system_temp_files())
        if self.web_cache:
            files_deleted_size += (analyze_web_cache())
        if self.web_cookies:
            files_deleted_size += (analyze_web_cookies())
        if self.old_windows_installs:
            files_deleted_size += (analyze_windows_install_files())
        if self.downloads_folder:
            files_deleted_size += (analyze_downloads_folders_files())

        self.size_of_files_deleted_label.SetLabelText("Files to be Deleted \n" + 
            "DocPY will attempt to delete \n" + 
            "{:.2f} GB of Files from your system.".format(files_deleted_size / (1024**3)))
        event.Skip()

    def clean_button_handler(self, event):  # wxGlade: MainPanel.<event_handler>
        print(self.temp_files,self.sys_temp_files,self.web_cache,self.web_cookies,self.recycle_bin,self.old_windows_installs,self.downloads_folder)
        files_deleted_size = 0
        if self.temp_files:
            files_deleted_size += (clean_user_temp_files())
        if self.sys_temp_files:
            files_deleted_size += (clean_system_temp_files())
        if self.web_cache:
            files_deleted_size += (clean_web_cache())
        if self.web_cookies:
            files_deleted_size += (clean_web_cookies())
        if self.recycle_bin:
            files_deleted_size += (empty_recycle_bin_files())
        if self.old_windows_installs:
            files_deleted_size += (clean_windows_install_files())
        if self.downloads_folder:
            files_deleted_size += (clean_downloads_folders_files())

        self.size_of_files_deleted_label.SetLabelText("Files Deleted \n{:.2f} GB of Files \nwere Deleted from your system.".format(files_deleted_size / (1024**3)))
        event.Skip()

# end of class MainPanel

class DocPyGUI(wx.App):
    def OnInit(self):
        self.DocPy = MainPanel(None, wx.ID_ANY, "")
        self.SetTopWindow(self.DocPy)
        self.DocPy.Show()
        return True

# end of class DocPyGUI

if __name__ == "__main__":

    DocPy = DocPyGUI(0)
    DocPy.MainLoop()
