#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Sun Nov 20 15:34:46 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainPanel(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainPanel.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((750, 464))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.V_Split = wx.SplitterWindow(self.panel_1, wx.ID_ANY)
        self.V_Split.SetMinimumPaneSize(20)
        sizer_1.Add(self.V_Split, 1, wx.EXPAND, 0)

        self.Options_Menu = wx.Panel(self.V_Split, wx.ID_ANY)

        Options_List = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_2, 1, wx.EXPAND, 0)

        self.temp_file_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_2.Add(self.temp_file_checkbox, 0, wx.ALL, 15)

        temp_file_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "User Temporary Files")
        sizer_2.Add(temp_file_label, 0, wx.ALL, 15)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_3, 1, wx.EXPAND, 0)

        self.sys_temp_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_3.Add(self.sys_temp_files_checkbox, 0, wx.ALL, 15)

        sys_temp_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "System Temporary Files")
        sizer_3.Add(sys_temp_files_label, 0, wx.ALL, 15)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_4, 1, wx.EXPAND, 0)

        self.web_cache_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_4.Add(self.web_cache_files_checkbox, 0, wx.ALL, 15)

        web_cache_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Web Cache")
        sizer_4.Add(web_cache_files_label, 0, wx.ALL, 15)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_5, 1, wx.EXPAND, 0)

        self.web_cookies_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_5.Add(self.web_cookies_files_checkbox, 0, wx.ALL, 15)

        web_cookies_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Web Cookies")
        sizer_5.Add(web_cookies_files_label, 0, wx.ALL, 15)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_6, 1, wx.EXPAND, 0)

        self.windows_installs_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_6.Add(self.windows_installs_files_checkbox, 0, wx.ALL, 15)

        windows_install_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Old Windows Install Files")
        sizer_6.Add(windows_install_files_label, 0, wx.ALL, 15)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_7, 1, wx.EXPAND, 0)

        self.recycle_bin_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_7.Add(self.recycle_bin_files_checkbox, 0, wx.ALL, 15)

        recycle_bin_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Recylcle Bin")
        sizer_7.Add(recycle_bin_files_label, 0, wx.ALL, 15)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_8, 1, wx.EXPAND, 0)

        self.user_downloads_files_checkbox = wx.CheckBox(self.Options_Menu, wx.ID_ANY, "")
        sizer_8.Add(self.user_downloads_files_checkbox, 0, wx.ALL, 15)

        user_downloads_files_label = wx.StaticText(self.Options_Menu, wx.ID_ANY, "Downloads Folder")
        sizer_8.Add(user_downloads_files_label, 0, wx.ALL, 15)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        Options_List.Add(sizer_12, 1, wx.EXPAND, 0)

        self.analyze_button = wx.Button(self.Options_Menu, wx.ID_ANY, "Analyze")
        sizer_12.Add(self.analyze_button, 0, wx.ALL, 15)

        self.clean_button = wx.Button(self.Options_Menu, wx.ID_ANY, "Clean")
        sizer_12.Add(self.clean_button, 0, wx.ALL, 15)

        self.Status_Pane = wx.Panel(self.V_Split, wx.ID_ANY)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)

        static_line_1 = wx.StaticLine(self.Status_Pane, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_11.Add(static_line_1, 0, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.Status_Pane, wx.ID_ANY)
        sizer_11.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.Status_Pane.SetSizer(sizer_11)

        self.Options_Menu.SetSizer(Options_List)

        self.V_Split.SplitVertically(self.Options_Menu, self.Status_Pane, 250)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class MainPanel

class DocPyGUI(wx.App):
    def OnInit(self):
        self.DocPy = MainPanel(None, wx.ID_ANY, "")
        self.SetTopWindow(self.DocPy)
        self.DocPy.Show()
        return True

# end of class DocPyGUI

if __name__ == "__main__":
    DocPy = DocPyGUI(0)
    DocPy.MainLoop()
